### ISSUE TITLE
Show last checked tag

### ISSUE THREAD

**Issue by johnjohndoe** [bierett/briefkastenkarte#1]
It would be nice to see when the information stored for a mailbox **has been checked the last time**. I know there are different tags used such as `last_checked`, `lastchecked`, `lastcheck`, `collection_times:lastcheck` as mentioned in this [German discussion about mailboxes in Hamburg](http://forum.openstreetmap.org/viewtopic.php?id=27602). There might be more.

Therefore, I would suggest to just show the tag whichever is used. That should be easy to implement.

**Comment by bierett** [comment]
I'm going to implement a check against the following tags:

``` xml
collection_times:lastcheck
lastcheck
last_checked
last_check
check_date
collection_times:last_check
```

in branch `feature/show-last-checked-tag-1`.

**Comment by bierett** [comment]
Implementation finished. Feature Branch was merged into `develop` (https://github.com/dbretschneider/briefkastenkarte.de/commit/ac02ed2eda7696dde6bc1c1564fa342a28921b18).

**Comment by johnjohndoe** [comment]
Looking forward to trying it out.

**Comment by johnjohndoe** [comment]
Nice. Small typo: "Briefkästen Älter als ein Jahr" should be "Briefkästen älter als ein Jahr".
