### ISSUE TITLE
Use release tags and changelog

### ISSUE THREAD

**Issue by johnjohndoe** [bierett/briefkastenkarte#3]
Please consider using **release tags** following [semantic versioning](http://semver.org). It's easy as this:

``` bash
$ git tag -a "v.1.0.0" -m "Short summary for this release."
$ git push origin master --tags"
```

The live website should also show the deployed version tag. Otherwise it is almost impossible to find out which code is running online. This will be useful for contributors to help.

Moreover, a _CHANGELOG.md_ file is very helpful to summarize the changes made since the last tag. You can find examples in many [other repositories](https://github.com/johnjohndoe/TypedPreferences/blob/master/CHANGELOG.md).

**Comment by bierett** [comment]
Create changelog and release tag:
- https://github.com/dbretschneider/briefkastenkarte.de/releases/tag/1.0.0
