### ISSUE TITLE
Large number of Overpass API requests

### ISSUE THREAD

**Issue by mmd-osm** [bierett/briefkastenkarte#8]
When browsing your map, I've noticed quite a large number of parallel requests to Overpass API, especially in lower zoom levels (12-14). This is relevant in the light of the current [Overpass Quotas](https://lists.openstreetmap.org/pipermail/talk/2015-April/072661.html) discussion. I would assume that your map as it is today is likely to be hit by HTTP 429 responses.

May I suggest to do some further analysis using Firebug or similar tools to reduce the number of requests. A few ideas in no particular order:
- add a rather small `[timeout:x]`
- maybe try larger bboxes
- limit the number of responses (`out qt 50`) per bbox and ask the user to zoom in for more details
- aggregating queries: http://gis.19327.n5.nabble.com/Query-Overpass-for-multiple-small-areas-td5838775.html
-  switch to the rumbler instance (which isn't limited per IP)
- maybe even file a bug with the [upstream library leaflet-layer-overpass](https://github.com/kartenkarsten/leaflet-layer-overpass) to optimize the total number of (parallel) Overpass API requests, while keeping a reasonable user experience.
- call `kill_my_queries` when moving the map, to abort current queries.

**Comment by k-nut** [comment]
It's probably a good idea to open an issue in the leaflet-layer-overpass repository. It should be solved there.
