### ISSUE TITLE
Are all the libraries used?

### ISSUE THREAD

**Issue by k-nut** [bierett/briefkastenkarte#9]
I just started migrating the dependencies to bower in order to improve maintainability, get updated about updates, licensing etc. via [versioneye](https://www.versioneye.com/).
It looks to me like some of the libraries that are included are not even used. So my question is. Do you actually use libraries like 
- jquery.cookie
- jquery ui
  Or can we just drop those?

**Comment by bierett** [comment]
At the moment both libraries aren't used. I will have a look on that at the FOSSGIS Hacking Event this weekend!
